name: Check Update Payload Info

on:
  workflow_dispatch:

jobs:
  check_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Install gdown and p7zip
        run: |
          pip install gdown
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Download update.zip From Google Drive
        run: |
          mkdir -p workspace
          gdown "16No1NoNDuTk_Ks4HT2SedWgTJFlzGbtl" -O workspace/update.zip

      - name: Extract Update Archive
        run: |
          7z x workspace/update.zip -oworkspace/update_extracted/

      - name: Set Up Payload Dumper Tool
        run: |
          # Download the tool binary directly (Fixed link)
          wget https://github.com -O workspace/payload_tool.tar.gz
          cd workspace
          tar -xzvf payload_tool.tar.gz
          chmod +x payload-dumper-go

      - name: Show Files Inside Payload
        run: |
          echo "===================================================="
          echo "          LISTING ALL FILES IN UPDATE ZIP           "
          echo "===================================================="
          cd workspace
          ./payload-dumper-go -l update_extracted/payload.bin
          echo "===================================================="
